ALTER TABLE schools ADD COLUMN IF NOT EXISTS teacher_code VARCHAR(20);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS student_code VARCHAR(20);
ALTER TABLE schools ADD COLUMN IF NOT EXISTS assistant_code VARCHAR(20);
